# Generated by Django 5.2.5 on 2025-08-29 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoEmergencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao', models.CharField(max_length=150, unique=True, verbose_name='Órgão')),
                ('telefones', models.CharField(help_text='Separe os números por vírgula.', max_length=200, verbose_name='Telefone(s) de Contato')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Contato Emergencial',
                'verbose_name_plural': 'Contatos Emergenciais',
                'ordering': ['orgao'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Final de Semana de Carnaval', max_length=150, verbose_name='Descrição')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Fim')),
            ],
            options={
                'verbose_name': 'Período de Plantão',
                'verbose_name_plural': 'Períodos de Plantão',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome da Secretaria')),
                ('escala_ativa', models.BooleanField(default=True, verbose_name='Escala Ativa')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.periodo')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
            },
        ),
        migrations.CreateModel(
            name='Plantonista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('telefones', models.CharField(help_text='Separe os números por vírgula. Ex: (11) 99999-8888, (11) 4798-0000', max_length=100, verbose_name='Telefone(s)')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantonistas', to='escala.secretaria')),
            ],
            options={
                'verbose_name': 'Plantonista',
                'verbose_name_plural': 'Plantonistas',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.AddField(
            model_name='periodo',
            name='plantonistas_escalados',
            field=models.ManyToManyField(related_name='periodos_escalados', through='escala.Escala', to='escala.plantonista'),
        ),
        migrations.AddField(
            model_name='escala',
            name='plantonista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.plantonista'),
        ),
        migrations.AlterUniqueTogether(
            name='escala',
            unique_together={('plantonista', 'periodo')},
        ),
    ]
